import type { IconType } from 'react-icons'
import {
  SiLinux,
  SiDocker,
  SiKubernetes,
  SiAnsible,
  SiTerraform,
  SiNginx,
  SiGit,
  SiGnubash,
  SiGitlab,
  SiJenkins,
  SiGooglecloud,
  SiPython,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiRubyonrails,
  SiPandas,
  SiScikitlearn,
  SiVercel,
  SiGithubactions,
  SiSolana,
  SiEthereum,
} from 'react-icons/si'
import {
  TbApi,
  TbBrandAws,
  TbBrandAzure,
  TbChess,
  TbInfinity,
  TbSatellite,
  TbDatabase,
} from 'react-icons/tb'

export const skillIcons: Record<string, IconType> = {
  Linux: SiLinux,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  Ansible: SiAnsible,
  Terraform: SiTerraform,
  'CI/CD': TbInfinity,
  Nginx: SiNginx,
  Git: SiGit,
  Bash: SiGnubash,
  'GitLab CI': SiGitlab,
  Jenkins: SiJenkins,
  AWS: TbBrandAws,
  Azure: TbBrandAzure,
  GCP: SiGooglecloud,
  Python: SiPython,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  React: SiReact,
  'Next.js': SiNextdotjs,
  'Node.js': SiNodedotjs,
  'Ruby on Rails': SiRubyonrails,
  'REST API': TbApi,
  SQL: TbDatabase,
  Pandas: SiPandas,
  'Scikit-learn': SiScikitlearn,
  'Elo Rating': TbChess,
  Vercel: SiVercel,
  'GitHub Actions': SiGithubactions,
  Solana: SiSolana,
  'Web3.py': SiEthereum,
  'Helius DAS': TbSatellite,
}
